import type { Metadata } from "next";
import { Cormorant_Garamond, Inter, DM_Serif_Display } from 'next/font/google'
import './globals.css'

const cormorant = Cormorant_Garamond({
  weight: ['400','600','700'],
  subsets: ['latin'],
  variable: '--font-serif'
})

const dmSerif = DM_Serif_Display({
  weight: ['400'],
  subsets: ['latin'],
  variable: '--font-displaySerif'
})

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-sans'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${cormorant.variable} ${inter.variable} ${dmSerif.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
